# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
}:

linkFarm "zig-packages" [
  {
    name = "riff_zig-2.0.0-rc.1-J7H0A97pTQCBkKJsLsOLBePDqIor-XWjrj_Yyp3XwMkS";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/refs/tags/2.0.0-rc.1.tar.gz";
      hash = "sha256-+J65oS92L5/aUS5rCGbZABjFbppxTBoKMFmNteU6Gx4=";
    };
  }
]
