# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "riff_zig-1.1.2-J7H0A0lxTADPiTM0n8qFOJER78SXIXJTG63AjeC768FG";
    path = fetchzip {
      url = "https://codeload.github.com/haruki7049/RIFF.zig/tar.gz/refs/tags/1.1.2";
      hash = "sha256-JNjOR4TvlPvJBGXE7zZ59XbgjUnnB9RPsEGMqMCJGAU=";
    };
  }
]
